# Docker


# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/backend/Dockerfile'
    #     tags: |
    #       $(tag)
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/frontend/Dockerfile'
    #     tags: |
    #       $(tag)
    - task: DockerCompose@0
      displayName: Build an image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1(3a35c19f-e098-4412-a1ce-a3fce7f26743)'
        azureContainerRegistry: '{"loginServer":"wedolistapp.azurecr.io", "id" : "/subscriptions/3a35c19f-e098-4412-a1ce-a3fce7f26743/resourceGroups/wedolist/providers/Microsoft.ContainerRegistry/registries/wedolistapp"}'
        dockerComposeFile: '$(Build.SourcesDirectory)/compose.yaml'
        action: 'Build services'
    - task: DockerCompose@0
      displayName: Push an image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1(3a35c19f-e098-4412-a1ce-a3fce7f26743)'
        azureContainerRegistry: '{"loginServer":"wedolistapp.azurecr.io", "id" : "/subscriptions/3a35c19f-e098-4412-a1ce-a3fce7f26743/resourceGroups/wedolist/providers/Microsoft.ContainerRegistry/registries/wedolistapp"}'
        dockerComposeFile: '$(Build.SourcesDirectory)/compose.yaml'
        action: 'Build services'
    - task: AzureContainerApps@1
      inputs:
        azureSubscription: 'Azure subscription 1(1)(3a35c19f-e098-4412-a1ce-a3fce7f26743)'
        acrName: 'wedolistapp'
        dockerfilePath: '$(Build.SourcesDirectory)/compose.yaml'
        containerAppName: 'wedolistapp.azurecr.io/sabudanakichditodolistwithfriends_frontend'
        resourceGroup: 'wedolist'
        targetPort: '3000'