# Docker


# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerCompose@0
      displayName: Build an image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1(3a35c19f-e098-4412-a1ce-a3fce7f26743)'
        azureContainerRegistry: '{"loginServer":"wedolistapp.azurecr.io", "id" : "/subscriptions/3a35c19f-e098-4412-a1ce-a3fce7f26743/resourceGroups/wedolist/providers/Microsoft.ContainerRegistry/registries/wedolistapp"}'
        dockerComposeFile: '$(Build.SourcesDirectory)/compose.yaml'
        action: 'Build services'
  - job: ACR_Push
    displayName: Push-to-ACR
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerCompose@0
      displayName: Push an image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1(3a35c19f-e098-4412-a1ce-a3fce7f26743)'
        azureContainerRegistry: '{"loginServer":"wedolistapp.azurecr.io", "id" : "/subscriptions/3a35c19f-e098-4412-a1ce-a3fce7f26743/resourceGroups/wedolist/providers/Microsoft.ContainerRegistry/registries/wedolistapp"}'
        dockerComposeFile: '$(Build.SourcesDirectory)/compose.yaml'
        action: 'Push services'
- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy-Frontend
    displayName: Deploy-Frontend
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureContainerApps@1
      inputs:
        azureSubscription: 'Azure subscription 1(1)(3a35c19f-e098-4412-a1ce-a3fce7f26743)'
        acrName: 'wedolistapp'
        imageToBuild: '$(Build.SourcesDirectory)/compose.yaml'
        imageToDeploy: 'wedolistapp.azurecr.io/sabudanakichditodolistwithfriends_frontend'
        containerAppName: 'wedolist'
        resourceGroup: 'wedolist'
        containerAppEnvironment: 'managedEnvironment-wedolist-88c7'
        targetPort: '3000'
        location: 'West US 2'
  - job: Deploy-Backend
    displayName: Deploy-Backend
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureContainerApps@1
      inputs:
        azureSubscription: 'Azure subscription 1(1)(3a35c19f-e098-4412-a1ce-a3fce7f26743)'
        acrName: 'wedolistapp'
        imageToBuild: '$(Build.SourcesDirectory)/compose.yaml'
        imageToDeploy: 'wedolistapp.azurecr.io/sabudanakichditodolistwithfriends_backend'
        containerAppName: 'wedolist'
        resourceGroup: 'wedolist'
        containerAppEnvironment: 'managedEnvironment-wedolist-88c7'
        targetPort: '3000'
        location: 'West US 2'